package com.example.zikstar.guardnews.Models;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;


    //Example of an autogenerated model from http://www.jsonschema2pojo.org
    //Just paste the json string and get this

public class Edition {

        @SerializedName("response")
        @Expose
        private Response23 response;

        public Response23 getResponse() {
            return response;
        }

        public void setResponse(Response23 response) {
            this.response = response;
        }

    }


